name: Build songs
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Get Repo
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Get Songbook
        uses: actions/checkout@v3
        with:
          repository: f-klubben/sangbog
          path: sangbog

      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Build songs
        run: python util/build_songs.py
#      - name: Commit to github action branch
#      - name: Create pull request
#        uses: peter-evans/create-pull-request@v4
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          branch: github-action
